# Desafio do Curso: Fluxo Completo de Dados e Machine Learning

Neste desafio, vocês deverão escolher um dataset de interesse e desenvolver o fluxo completo de análise e modelagem, desde a coleta e a compreensão dos dados até a interpretação dos resultados.

A ideia é que vocês apliquem, de forma prática, todas as etapas fundamentais de um projeto de Ciência de Dados e Aprendizado de Máquina, incluindo:

- limpeza e preparação dos dados;
- tratamento de valores ausentes, inconsistências e ruídos;
- transformação e normalização das variáveis;
- feature engineering e criação de novas informações relevantes;
- seleção de variáveis e validação de hipóteses;
- modelagem com algoritmos adequados ao problema;
- avaliação do desempenho do modelo;
- análise crítica dos resultados e possíveis melhorias.

Este é um desafio de aplicação prática. O curso forneceu a base, os conceitos e as ferramentas iniciais, mas ele não ensina tudo sobre cada etapa de um projeto real. O aluno precisará usar o impulso e a curiosidade adquiridos no curso para pesquisar, estudar por conta própria e aprender a resolver problemas que aparecem ao longo do processo.

Além do aprendizado, há uma **recompensa especial** para os melhores: um exemplar lacrado do livro *Mãos a Obra: Aprendizado de Máquina* para quem vencer o desafio ou para os alunos sorteados entre os que ficarem entre as primeiras posições.

O objetivo não é apenas entregar um notebook bonito, mas demonstrar que vocês conseguem construir um fluxo completo, tomar decisões técnicas com embasamento e apresentar resultados coerentes com o problema escolhido.

# Como enviar o desafio

O desafio pode ser enviado para os instrutores por meio de um Pull Request para adicionar o arquivo desafio/<seu_nome>.ipynb no repositório.

Caso o aluno não tenha domínio da tecnologia necessária para realizar o envio dessa forma, o desafio também pode ser enviado a um email de um dos lecionadores:

>brsrocha.pi@gmail.com  
>guihiginoo@gmail.com

# Import de Bibliotecas Principais

In [1]:
# Essenciais
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Modelos que vimos em aula
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

# == SE PRECISAR DE MAIS BIBLIOTECAS, ADICIONE AQUI ==
# ...

# Escolha do Dataset
Escolha um dos 2 datasets já selecionados abaixo, importando-o para o `DataFrame` 'df' já preparado. Um dataset é para modelos de *classificação*, enquanto o outro é para *regressão*. Boa sorte!

---

### CLASSIFICAÇÃO - Dataset Bank Marketing (Adesão de Clientes)
Este dataset contém dados de adesão de clientes por meio de campanhas de marketing via telefone. A coluna `y` contém as labels de target para os clientes que contrataram um depósito com o banco (yes) ou não (no). O objetivo é, após limpar e preparar os dados, treinar um modelo capaz de *receber informações de clientes* coletadas na campanha de marketing, e prever se eles vão aderir ou não ao banco. Pontos bônus caso preveja não somente `yes` ou `no`, mas também a `probabilidade` do cliente aderir, e um relatório de como aumentar essa probabilidade.

Mais informações em *https://archive.ics.uci.edu/dataset/222/bank+marketing*

In [2]:
df = pd.read_csv('bank-full.csv', sep=';')
df.head()
# ...

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

---

### REGRESSÃO - Energy Efficiency (Eficiência Energética)
Este dataset contém dados de 12 diferentes tipos de construções e seus respectivos dados. Possui duas colunas target contínuas, a `Y1 (Heating Load)` - Carga térmica de aquecimento, e a `Y2 (Cooling Load)` - Carga térmica de resfriamento. O objetivo é limpar e preparar os dados, e treinar um modelo capaz de prever, com base nas características de cada construção, qual valor de `Y1` e qual valor de `Y2` ela possuirá. Pontos bônus se houver no final uma forma de combinar Y1 e Y2 em uma só medida.

Mais informações em *https://archive.ics.uci.edu/dataset/242/energy+efficiency*

In [6]:
df = pd.read_excel('ENB2012_data.xlsx')
df.head()
# ...

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28