In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:

dfPayments = pd.read_csv("archive/olist_order_payments_dataset.csv")
dfProducts = pd.read_csv("archive/olist_products_dataset.csv")
dfOrders = pd.read_csv("archive/olist_orders_dataset.csv")
dfOrdersItens = pd.read_csv("archive/olist_order_items_dataset.csv")

In [26]:
df = pd.merge(dfOrders, dfOrdersItens, on='order_id', how='inner')
df = pd.merge(df, dfProducts, on='product_id', how='inner')
df = pd.merge(df, dfPayments, on='order_id', how='inner')
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,1,credit_card,1,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,3,voucher,1,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,2,voucher,1,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,178.0,1.0,400.0,19.0,13.0,19.0,1,boleto,1,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,232.0,1.0,420.0,24.0,19.0,21.0,1,credit_card,3,179.12

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117601 entries, 0 to 117600
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117601 non-null  object
 1   customer_id                    117601 non-null  object
 2   order_status                   117601 non-null  object
 3   order_purchase_timestamp       117601 non-null  object
 4   order_approved_at              117586 non-null  object
 5   order_delivered_carrier_date   116356 non-null  object
 6   order_delivered_customer_date  115034 non-null  object
 7   order_estimated_delivery_date  117601 non-null  object
 8   order_item_id                  117601 non-null  int64
 9   product_id                     117601 non-null  object
 10  seller_id                      117601 non-null  object
 11  shipping_limit_date            117601 non-null  object
 12  price                          117601 non-null  float64
 13  freight_value                  117601 non-null  float64
 14  product_category_name          115903 non-null  object
 15  product_name_lenght            115903 non-null  float64
 16  product_description_lenght     115903 non-null  float64
 17  product_photos_qty             115903 non-null  float64
 18  product_weight_g               117581 non-null  float64
 19  product_length_cm              117581 non-null  float64
 20  product_height_cm              117581 non-null  float64
 21  product_width_cm               117581 non-null  float64
 22  payment_sequential             117601 non-null  int64
 23  payment_type                   117601 non-null  object
 24  payment_installments           117601 non-null  int64
 25  payment_value                  117601 non-null  float64
dtypes: float64(10), int64(3), object(13)
memory usage: 23.3+ MB

In [28]:
df = df.drop(columns=[
    'order_id', 'product_id', 'seller_id', 'customer_id',
    'order_purchase_timestamp', 'order_approved_at',
    'order_delivered_carrier_date', 'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'payment_sequential', 'payment_installments',
    'product_name_lenght', 'product_description_lenght',
    'product_photos_qty', 'shipping_limit_date', 'order_status'
], errors='ignore')
df.head()

,order_item_id,price,freight_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_type,payment_value
0,1,29.99,8.72,utilidades_domesticas,500.0,19.0,8.0,13.0,credit_card,18.12
1,1,29.99,8.72,utilidades_domesticas,500.0,19.0,8.0,13.0,voucher,2.00
2,1,29.99,8.72,utilidades_domesticas,500.0,19.0,8.0,13.0,voucher,18.59
3,1,118.70,22.76,perfumaria,400.0,19.0,13.0,19.0,boleto,141.46
4,1,159.90,19.22,automotivo,420.0,24.0,19.0,21.0,credit_card,179.12

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117601 entries, 0 to 117600
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   order_item_id          117601 non-null  int64
 1   price                  117601 non-null  float64
 2   freight_value          117601 non-null  float64
 3   product_category_name  115903 non-null  object
 4   product_weight_g       117581 non-null  float64
 5   product_length_cm      117581 non-null  float64
 6   product_height_cm      117581 non-null  float64
 7   product_width_cm       117581 non-null  float64
 8   payment_type           117601 non-null  object
 9   payment_value          117601 non-null  float64
dtypes: float64(7), int64(1), object(2)
memory usage: 9.0+ MB